eureka:
  client:
    register-with-eureka: true
    fetch_registry: true
    service-url:
      defaultZone: http://registry-service.eastus.azurecontainer.io:8761/eureka/
  instance:
    hostname: localhost
